

export default {
    products: [
        {
            _id: 1,
            name: 'Blue Vindo',
            price: '140.00',
            stock: 12,
            category: 'Headgear', 
            type: 'construction',
            brand: 'WM',
            rating: '7.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 2,
            name: 'Blue Strap',
            price: '100.98',
            stock: 12,
            category: 'Headgear',
            type: 'racing',
            brand: 'WM',
            rating: '7.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 3,
            name: 'Boxer 5000',
            price: '139.00.',
            stock: 12,
            category: 'Headgear',
            type: 'heavy_padding',
            brand: 'WM',
            rating: '9.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 4,
            name: 'Banoi Netti',
            price: '150.97',
            stock: 12,
            category: 'Headgear',
            type: 'racing',
            brand: 'WM',
            rating: '4.5',
            numReviews: 130,
            trending: true,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 5,
            name: 'Holes Blackie',
            price: '149.00',
            stock: 12,
            category: 'Headgear',
            type: 'racing',
            brand: 'WM',
            rating: '4.5',
            numReviews: 140,
            trending: true,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 6,
            name: 'Holes Reddie',
            price: '199.98',
            stock: 12,
            category: 'Headgear',
            type: 'racing',
            brand: 'WM',
            rating: '4.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 7,
            name: 'Orange medie',
            price: '499.98',
            stock: 12,
            category: 'Headgear',
            type: 'racing',
            brand: 'WM',
            rating: '8.5',
            numReviews: 142,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 8,
            name: 'Pinkito Dei',
            price: '199.98',
            stock: 12,
            category: 'Headgear',
            type: 'riding',
            brand: 'WM',
            rating: '6.5',
            numReviews: 50,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 9,
            name: 'Cantebury H1',
            price: '199.98',
            stock: 12,
            category: 'sport',
            type: '',
            brand: 'WM',
            rating: '9.3',
            numReviews: 70,
            new: true,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 10,
            name: 'Comfy Nieti Headgear',
            price: '499.98',
            stock: 12,
            category: 'Headgear',
            type: 'heavy_padding',
            brand: 'WM',
            rating: '8.1',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 11,
            name: 'Construction Helmet',
            price: '69.98',
            stock: 12,
            category: 'Headgear',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 12,
            name: 'Blue Vindo',
            price: '140.00',
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 13,
            name: 'Blue Strap',
            price: '100.98',
            stock: 12,
            category: 'Clothing',
            type: 'racing',
            brand: 'WM',
            rating: '7.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 14,
            name: 'Boxer 5000',
            price: '139.00.',
            stock: 12,
            category: 'Clothing',
            type: 'heavy_padding',
            brand: 'WM',
            rating: '9.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 15,
            name: 'Banoi Netti',
            price: '150.97',
            stock: 12,
            category: 'Clothing',
            type: 'racing',
            brand: 'WM',
            rating: '4.5',
            numReviews: 130,
            new: true,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 16,
            name: 'Holes Blackie',
            price: '149.00',
            stock: 12,
            category: 'Clothing',
            type: 'racing',
            brand: 'WM',
            rating: '4.5',
            numReviews: 140,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 17,
            name: 'Holes Reddie',
            price: '199.98',
            stock: 12,
            category: 'Clothing',
            type: 'racing',
            brand: 'WM',
            rating: '4.5',
            numReviews: 10,
            new: true,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 18,
            name: 'Orange medie',
            price: '499.98',
            stock: 12,
            category: 'Clothing',
            type: 'racing',
            brand: 'WM',
            rating: '8.5',
            numReviews: 142,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 19,
            name: 'Pinkito Dei',
            price: '199.98',
            stock: 12,
            category: 'Clothing',
            type: 'riding',
            brand: 'WM',
            rating: '6.5',
            numReviews: 50,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 20,
            name: 'Cantebury Clothing',
            price: '199.98',
            stock: 12,
            category: 'sport',
            type: '',
            brand: 'WM',
            rating: '9.3',
            numReviews: 70,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 21,
            name: 'Comfy Nieti Clothing',
            price: '499.98',
            stock: 12,
            category: 'Clothing',
            type: 'heavy_padding',
            brand: 'WM',
            rating: '8.1',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 22,
            name: 'Construction Helmet',
            price: '69.98',
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 23,
            name: 'Construction Helmet',
            price: '69.98',
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 24,
            name: 'Construction Helmet',
            price: '69.98',
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 25,
            name: 'Construction Helmet',
            price: '69.98',
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 26,
            name: 'Construction Helmet',
            price: '69.98',
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 27,
            name: 'Construction Helmet',
            price: '69.98',
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            trending: true,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
    ]
}