export const PROD_LIST_REQUEST = 'PROD_LIST_REQUEST';
export const PROD_LIST_SUCCESS = 'PROD_LIST_SUCCESS';
export const PROD_LIST_FAIL = 'PROD_LIST_FAIL';
export const PROD_LIST_ITEM = 'PROD_LIST_ITEM';

export const PROD_DETAIL_REQUEST = 'PROD_DETAIL_REQUEST';
export const PROD_DETAIL_SUCCESS = 'PROD_DETAIL_SUCCESS';
export const PROD_DETAIL_FAIL = 'PROD_DETAIL_FAIL';

export const PROD_UPDATE_REQUEST = 'PROD_UPDATE_REQUEST';
export const PROD_UPDATE_SUCCESS = 'PROD_UPDATE_SUCCESS';
export const PROD_UPDATE_FAIL = 'PROD_UPDATE_FAIL';

export const PROD_SAVE_REQUEST = 'PROD_SAVE_REQUEST';
export const PROD_SAVE_SUCCESS = 'PROD_SAVE_SUCCESS';
export const PROD_SAVE_FAIL = 'PROD_SAVE_FAIL';

export const PROD_DELETE_REQUEST = 'PROD_DELETE_REQUEST';
export const PROD_DELETE_SUCCESS = 'PROD_DELETE_SUCCESS';
export const PROD_DELETE_FAIL = 'PROD_DELETE_FAIL';

export const PROD_CATEGORY_LIST_REQUEST = 'PROD_CATEGORY_LIST_REQUEST';
export const PROD_CATEGORY_LIST_SUCCESS = 'PROD_CATEGORY_LIST_SUCCESS';
export const PROD_CATEGORY_LIST_FAIL = 'PROD_CATEGORY_LIST_FAIL';

export const PROD_NEW_LIST_REQUEST = 'PROD_NEW_LIST_REQUEST';
export const PROD_NEW_LIST_SUCCESS = 'PROD_NEW_LIST_SUCCESS';
export const PROD_NEW_LIST_FAIL = 'PROD_NEW_LIST_FAIL';
export const PROD_NEW_LIST_ITEM = 'PROD_NEW_LIST_ITEM';

export const PROD_NEW_DETAIL_REQUEST = 'PROD_NEW_DETAIL_REQUEST';
export const PROD_NEW_DETAIL_SUCCESS = 'PROD_NEW_DETAIL_SUCCESS';
export const PROD_NEW_DETAIL_FAIL = 'PROD_NEW_DETAIL_FAIL';

export const PROD_NEW_SAVE_REQUEST = 'PROD_NEW_SAVE_REQUEST';
export const PROD_NEW_SAVE_SUCCESS = 'PROD_NEW_SAVE_SUCCESS';
export const PROD_NEW_SAVE_FAIL = 'PROD_NEW_SAVE_FAIL';

export const PROD_TRENDING_LIST_REQUEST = 'PROD_TRENDING_LIST_REQUEST';
export const PROD_TRENDING_LIST_SUCCESS = 'PROD_TRENDING_LIST_SUCCESS';
export const PROD_TRENDING_LIST_FAIL = 'PROD_TRENDING_LIST_FAIL';
export const PROD_TRENDING_LIST_ITEM = 'PROD_TRENDING_LIST_ITEM';

export const PROD_TRENDING_DETAIL_REQUEST = 'PROD_TRENDING_DETAIL_REQUEST';
export const PROD_TRENDING_DETAIL_SUCCESS = 'PROD_TRENDING_DETAIL_SUCCESS';
export const PROD_TRENDING_DETAIL_FAIL = 'PROD_TRENDING_DETAIL_FAIL';

export const PROD_TRENDING_SAVE_REQUEST = 'PROD_TRENDING_SAVE_REQUEST';
export const PROD_TRENDING_SAVE_SUCCESS = 'PROD_TRENDING_SAVE_SUCCESS';
export const PROD_TRENDING_SAVE_FAIL = 'PROD_TRENDING_SAVE_FAIL';