import black from './images/black.jpg';
//headgear

import blue from './assets/Headgear/blue.jpg';
import bluestrap from './assets/Headgear/bluestrap.jpg';
import boxingred from './assets/Headgear/boxingred.jpg';
import bus from './assets/Headgear/bus.jpg';
import holes from './assets/Headgear/holes.jpg';
import holesred from './assets/Headgear/holesred.jpg';
import orange from './assets/Headgear/orange.png';
import pink from './assets/Headgear/pink.jpg';
import rugby from './assets/Headgear/rugby.jpg';
import white from './assets/Headgear/white.jpg';
import yellow from './assets/Headgear/yellow.jpg';

//clothing
import belt from './assets/Clothing/belt.jpg';
import blackmuffs from './assets/Clothing/blackmuffs.jpg';
import Dunlop from './assets/Clothing/Dunlop.jpg';
import gumboots from './assets/Clothing/gumboots.jpg';
import latex from './assets/Clothing/belt.jpg';
import orangesuit from './assets/Clothing/orangesuit.jpeg';
import plugs from './assets/Clothing/plugs.jpg';
import plugstwo from './assets/Clothing/plugstwo.jpg';
import qualitygloves from './assets/Clothing/qualitygloves.jpg';
import redmuffs from './assets/Clothing/redmuffs.jpg';
import safejackets from './assets/Clothing/safejackets.jpg';
import safety from './assets/Clothing/safety.jpg';
import straps from './assets/Clothing/straps.jpeg';
import thickgloves from './assets/Clothing/thickgloves.jpg';
import tyvek from './assets/Clothing/tyvek.jpg';
import whitegloves from './assets/Clothing/whitegloves.jpg';

export default {
    productss: [
        {
            _id: 1,
            name: 'Blue Vindo',
            price: '$140.00',
            image: blue,
            stock: 12,
            category: 'Headgear',
            type: 'construction',
            brand: 'WM',
            rating: '7.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 2,
            name: 'Blue Strap',
            price: '$100.98',
            image: bluestrap,
            stock: 12,
            category: 'Headgear',
            type: 'racing',
            brand: 'WM',
            rating: '7.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 3,
            name: 'Boxer 5000',
            price: '$139.00.',
            image: boxingred,
            stock: 12,
            category: 'Headgear',
            type: 'heavy_padding',
            brand: 'WM',
            rating: '9.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 4,
            name: 'Banoi Netti',
            price: '$150.97',
            image: bus,
            stock: 12,
            category: 'Headgear',
            type: 'racing',
            brand: 'WM',
            rating: '4.5',
            numReviews: 130,
            trending: true,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 5,
            name: 'Holes Blackie',
            price: '$149.00',
            image: holes,
            stock: 12,
            category: 'Headgear',
            type: 'racing',
            brand: 'WM',
            rating: '4.5',
            numReviews: 140,
            trending: true,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 6,
            name: 'Holes Reddie',
            price: '$199.98',
            image: holesred,
            stock: 12,
            category: 'Headgear',
            type: 'racing',
            brand: 'WM',
            rating: '4.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 7,
            name: 'Orange medie',
            price: '$499.98',
            image: orange,
            stock: 12,
            category: 'Headgear',
            type: 'racing',
            brand: 'WM',
            rating: '8.5',
            numReviews: 142,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 8,
            name: 'Pinkito Dei',
            price: '$199.98',
            image: pink,
            stock: 12,
            category: 'Headgear',
            type: 'riding',
            brand: 'WM',
            rating: '6.5',
            numReviews: 50,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 9,
            name: 'Cantebury H1',
            price: '$199.98',
            image: rugby,
            stock: 12,
            category: 'sport',
            type: '',
            brand: 'WM',
            rating: '9.3',
            numReviews: 70,
            new: true,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 10,
            name: 'Comfy Nieti Headgear',
            price: '$499.98',
            image: white,
            stock: 12,
            category: 'Headgear',
            type: 'heavy_padding',
            brand: 'WM',
            rating: '8.1',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 11,
            name: 'Construction Helmet',
            price: '$69.98',
            image: yellow,
            stock: 12,
            category: 'Headgear',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 12,
            name: 'Blue Vindo',
            price: '$140.00',
            image: belt,
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 13,
            name: 'Blue Strap',
            price: '$100.98',
            image: blackmuffs,
            stock: 12,
            category: 'Clothing',
            type: 'racing',
            brand: 'WM',
            rating: '7.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 14,
            name: 'Boxer 5000',
            price: '$139.00.',
            image: Dunlop,
            stock: 12,
            category: 'Clothing',
            type: 'heavy_padding',
            brand: 'WM',
            rating: '9.5',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 15,
            name: 'Banoi Netti',
            price: '$150.97',
            image: gumboots,
            stock: 12,
            category: 'Clothing',
            type: 'racing',
            brand: 'WM',
            rating: '4.5',
            numReviews: 130,
            new: true,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 16,
            name: 'Holes Blackie',
            price: '$149.00',
            image: latex,
            stock: 12,
            category: 'Clothing',
            type: 'racing',
            brand: 'WM',
            rating: '4.5',
            numReviews: 140,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 17,
            name: 'Holes Reddie',
            price: '$199.98',
            image: orangesuit,
            stock: 12,
            category: 'Clothing',
            type: 'racing',
            brand: 'WM',
            rating: '4.5',
            numReviews: 10,
            new: true,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 18,
            name: 'Orange medie',
            price: '$499.98',
            image: plugs,
            stock: 12,
            category: 'Clothing',
            type: 'racing',
            brand: 'WM',
            rating: '8.5',
            numReviews: 142,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 19,
            name: 'Pinkito Dei',
            price: '$199.98',
            image: plugstwo,
            stock: 12,
            category: 'Clothing',
            type: 'riding',
            brand: 'WM',
            rating: '6.5',
            numReviews: 50,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 20,
            name: 'Cantebury Clothing',
            price: '$199.98',
            image: qualitygloves,
            stock: 12,
            category: 'sport',
            type: '',
            brand: 'WM',
            rating: '9.3',
            numReviews: 70,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 21,
            name: 'Comfy Nieti Clothing',
            price: '$499.98',
            image: redmuffs,
            stock: 12,
            category: 'Clothing',
            type: 'heavy_padding',
            brand: 'WM',
            rating: '8.1',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 22,
            name: 'Construction Helmet',
            price: '$69.98',
            image: safejackets,
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 23,
            name: 'Construction Helmet',
            price: '$69.98',
            image: safety,
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 24,
            name: 'Construction Helmet',
            price: '$69.98',
            image: straps,
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 25,
            name: 'Construction Helmet',
            price: '$69.98',
            image: thickgloves,
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 26,
            name: 'Construction Helmet',
            price: '$69.98',
            image: tyvek,
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
        {
            _id: 27,
            name: 'Construction Helmet',
            price: '$69.98',
            image: whitegloves,
            stock: 12,
            category: 'Clothing',
            type: 'construction',
            brand: 'WM',
            rating: '7',
            numReviews: 10,
            trending: true,
            description: 'The product description will come here and will occupy about two or three lines, not too long.Hello, hi, i am just typing to make this text longer.',
        },
    ]
}